name: Django

on:
 push:
  branches:
  - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Django image
      run: |
          docker build . -t khalidtarek7/khalid_django
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push khalidtarek7/khalid_django
