name: Django

on:
 push:
  branches:
  - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Django image
      run: |
          docker build . -t khalid/django
          docker login -u khalidtarek7 -p KhalidTarek7!
          docker push khalid/django
